amcl:  # not used during SLAM
  ros__parameters: {}

bt_navigator:
  ros__parameters:
    use_sim_time: True
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    plugin_lib_names: ["nav2_compute_path_to_pose_action_bt_node",
                       "nav2_follow_path_action_bt_node",
                       "nav2_is_path_valid_condition_bt_node",
                       "nav2_goal_reached_condition_bt_node",
                       "nav2_rate_controller_bt_node",
                       "nav2_recovery_node_bt_node",
                       "nav2_pipeline_sequence_bt_node"]

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: False
      min_vel_x: 0.0
      max_vel_x: 0.6
      max_vel_theta: 1.2
      acc_lim_x: 1.0
      acc_lim_theta: 1.5
      decel_lim_x: -1.0
      decel_lim_theta: -1.5
      vx_samples: 20
      vtheta_samples: 20
      sim_time: 2.0
      linear_granularity: 0.05
      angular_granularity: 0.025
      xy_goal_tolerance: 0.15
      yaw_goal_tolerance: 0.15
      transform_tolerance: 0.2
      base_frame_id: base_link
      odom_topic: odom

planner_server:
  ros__parameters:
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5

smoother_server:
  ros__parameters:
    use_sim_time: True
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"

behavior_server:
  ros__parameters:
    use_sim_time: True

waypoint_follower:
  ros__parameters:
    use_sim_time: True

global_costmap:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 2.0
    publish_frequency: 2.0
    resolution: 0.05
    rolling_window: False
    size_x: 50
    size_y: 50
    footprint_radius: 0.20
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: scan
      scan:
        topic: scan
        max_obstacle_height: 1.0
        clearing: True
        marking: True
        inf_is_valid: True
        data_type: LaserScan
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.5

local_costmap:
  ros__parameters:
    use_sim_time: True
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 10.0
    publish_frequency: 5.0
    resolution: 0.05
    rolling_window: True
    width: 6.0
    height: 6.0
    footprint_radius: 0.20
    plugins: ["obstacle_layer", "inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: scan
      scan:
        topic: scan
        max_obstacle_height: 1.0
        clearing: True
        marking: True
        inf_is_valid: True
        data_type: LaserScan
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.5

# Lifecycle manager
lifecycle_manager:
  ros__parameters:
    use_sim_time: True
    autostart: True
    node_names: ["controller_server", "planner_server", "smoother_server",
                 "behavior_server", "bt_navigator", "waypoint_follower",
                 "global_costmap", "local_costmap"]
