slam_toolbox:
  ros__parameters:
    use_sim_time: true
    slam_params:
      odom_frame: odom
      map_frame: map
      base_frame: base_link
      scan_topic: scan
      mode: mapping
    # Good defaults for sim
    resolution: 0.05
    minimum_time_interval: 0.5
    max_laser_range: 8.0
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.05
